const colors: Record<string, string> = {
  active: "bg-emerald-400/10 text-emerald-400",
  connected: "bg-emerald-400/10 text-emerald-400",
  ready: "bg-emerald-400/10 text-emerald-400",
  succeeded: "bg-emerald-400/10 text-emerald-400",
  completed: "bg-emerald-400/10 text-emerald-400",
  operational: "bg-emerald-400/10 text-emerald-400",
  unknown: "bg-zinc-400/10 text-zinc-400",
  checking: "bg-blue-400/10 text-blue-400",
  reauth_required: "bg-amber-400/10 text-amber-400",
  action_required: "bg-orange-400/10 text-orange-400",
  permission_required: "bg-amber-400/10 text-amber-400",
  temporarily_restricted: "bg-red-400/10 text-red-400",
  possibly_suspended: "bg-red-400/10 text-red-400",
  provider_unavailable: "bg-blue-400/10 text-blue-400",
  pending: "bg-amber-400/10 text-amber-400",
  planned: "bg-zinc-400/10 text-zinc-400",
  queued: "bg-blue-400/10 text-blue-400",
  publishing: "bg-violet-400/10 text-violet-400",
  retry_scheduled: "bg-amber-400/10 text-amber-400",
  processing: "bg-blue-400/10 text-blue-400",
  scheduled: "bg-violet-400/10 text-violet-400",
  running: "bg-violet-400/10 text-violet-400",
  paused: "bg-amber-400/10 text-amber-400",
  cancelled: "bg-zinc-400/10 text-zinc-500",
  completed_with_errors: "bg-amber-400/10 text-amber-400",
  dead_letter: "bg-red-400/10 text-red-400",
  failed_permanent: "bg-red-400/10 text-red-400",
  degraded: "bg-red-400/10 text-red-400",
  error: "bg-red-400/10 text-red-400",
  failed: "bg-red-400/10 text-red-400",
  suspended: "bg-red-400/10 text-red-400",
};

const labels: Record<string, string> = {
  active: "Ativo",
  connected: "Conectada",
  ready: "Pronta",
  succeeded: "Publicado",
  completed: "Concluída",
  operational: "Operacional",
  unknown: "Desconhecido",
  checking: "Verificando",
  reauth_required: "Reconectar",
  action_required: "Ação necessária",
  permission_required: "Permissão necessária",
  temporarily_restricted: "Restrição temporária",
  possibly_suspended: "Possível suspensão",
  provider_unavailable: "Meta indisponível",
  pending: "Pendente",
  planned: "Planejado",
  queued: "Na fila",
  publishing: "Publicando",
  retry_scheduled: "Nova tentativa",
  processing: "Processando",
  scheduled: "Agendada",
  running: "Executando",
  paused: "Pausada",
  cancelled: "Cancelada",
  completed_with_errors: "Concluída com erros",
  dead_letter: "Falha definitiva",
  failed_permanent: "Falha permanente",
  degraded: "Degradado",
  error: "Erro",
  failed: "Falhou",
  suspended: "Suspensa",
};

export function StatusBadge({ status }: { status: string }) {
  return (
    <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-semibold ${colors[status] ?? "bg-zinc-700/40 text-zinc-400"}`}>
      {labels[status] ?? status.replaceAll("_", " ")}
    </span>
  );
}
